version: '3'

services:
    #PHP Service
    query-watcher:
        build:
            context: ""
            dockerfile: Dockerfile
        container_name: query-watcher
        tty: true
        environment:
            SERVICE_NAME: query-watcher
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - yorcreative

networks:
    yorcreative:
        driver: bridge

