<?php

namespace YorCreative\QueryWatcher\Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Http;
use YorCreative\QueryWatcher\Events\QueryEvent;
use YorCreative\QueryWatcher\Listeners\QueryListener;
use YorCreative\QueryWatcher\Tests\TestCase;
use YorCreative\QueryWatcher\Tests\Utility\Models\DemoOwner;
use YorCreative\QueryWatcher\Tests\Utility\Models\Test;

class CaptureQueryTest extends TestCase
{
    use DatabaseTransactions;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::trackQueries();
    }

    /**
     * @test
     * @group Feature
     */
    public function it_can_capture_a_query_without_auth_user()
    {
        HTTP::fake();

        (new Test())
            ->newQuery()
            ->get();

        $this->assertEventBroadcasted(
            'query.event'
        );

        $this->assertQueryCountMatches(1);
    }

    /**
     * @test
     * @group Feature
     */
    public function it_can_capture_a_query_with_auth_user()
    {
        HTTP::fake();

        $user = DemoOwner::factory()->create();

        Auth::login($user);

        (new Test())
            ->newQuery()
            ->get();

        $this->assertEventBroadcasted(
            'query.event'
        );

        $this->assertQueryCountMatches(2);
    }

    /**
     * @test
     * @group Feature
     */
    public function it_is_listening_for_query_event()
    {
        Event::fake();

        Event::assertListening(QueryEvent::class, QueryListener::class);
    }
}
