<?php

namespace YorCreative\QueryWatcher\Tests\Integration\Strategies;

use Illuminate\Support\Facades\Log;
use YorCreative\QueryWatcher\Models\QueryModel;
use YorCreative\QueryWatcher\Strategies\NotificationStrategy\NotificationChannelInterface;
use YorCreative\QueryWatcher\Strategies\NotificationStrategy\NotificationStrategy;
use YorCreative\QueryWatcher\Tests\TestCase;
use YorCreative\QueryWatcher\Transformers\QueryTransformer;

class NotificationStrategyTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @group Integration
     * @group Strategies
     */
    public function it_can_send_notification_to_channel()
    {
        $aChannel = new Channel;

        $notificationStrategy = (new NotificationStrategy());
        $notificationStrategy->setChannel($aChannel);

        $notificationStrategy->notify(new QueryModel(QueryTransformer::transform($this->queryEvent)));

        Log::shouldReceive('notify');
    }
}

class Channel implements NotificationChannelInterface
{
    public function isEnabled(): bool
    {
        return true;
    }

    public function notify(QueryModel $model): void
    {
        Log::info('notify');
    }
}
