<?php

namespace YorCreative\QueryWatcher\Tests;

use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Http;
use YorCreative\QueryWatcher\Transformers\TriggerTransformer;

class TriggerTransformerTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        HTTP::fake();
        Event::fake();
    }

    /**
     * @test
     * @group Transformers
     * @group Unit
     */
    public function it_can_transform_trigger_and_context_into_array()
    {
        $this->assertEquals(
            [
                'action' => 'Console',
                'context' => [
                    'url' => null,
                    'input' => null,
                ],
            ],
            TriggerTransformer::transform()
        );
    }
}
