<?php

namespace YorCreative\QueryWatcher\Tests\Unit\Strategies\Channels;

use Illuminate\Support\Facades\Http;
use YorCreative\QueryWatcher\Strategies\NotificationStrategy\Channels\Discord;
use YorCreative\QueryWatcher\Tests\TestCase;

class DiscordTest extends TestCase
{
    public Discord $discordChannel;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->discordChannel = new Discord();
    }

    /**
     * @test
     * @group Unit
     * @group Channels
     * @group Strategies
     */
    public function it_can_send_http_request_to_discord()
    {
        Http::fake();

        $this->discordChannel->notify($this->queryModel);

        Http::assertSentCount(1);
    }

    /**
     * @test
     * @group Unit
     * @group Channels
     * @group Strategies
     */
    public function it_can_determine_that_discord_channel_is_enabled()
    {
        app()['config']->set('querywatcher.channels.discord.enabled', true);
        $this->assertTrue($this->discordChannel->isEnabled());
    }

    /**
     * @test
     * @group Unit
     * @group Channels
     * @group Strategies
     */
    public function it_can_determine_that_discord_channel_is_not_enabled()
    {
        app()['config']->set('querywatcher.channels.discord.enabled', false);
        $this->assertFalse($this->discordChannel->isEnabled());
    }
}
